services:
  - type: web
    name: chat-bot
    runtime: python
    buildCommand: "poetry install --no-root"
    startCommand: "poetry run gunicorn app:app -b 0.0.0.0:10000"
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: GOOGLE_API_KEY
        sync: false
      - key: GOOGLE_ENGINE_ID
        sync: false
      - key: SECRET_KEY
        sync: false
